description = "Generate a Conventional Commit message from provided context"

prompt = """
You are assisting with crafting a Conventional Commits compliant message for this repository.

Follow these strict rules:
- Allowed types: feat, fix, refactor, style, perf, test, docs, chore, ci, revert
- Optional scope in parentheses when clear (e.g., fix(tree): ...)
- Description: imperative mood, lowercase first letter, no trailing period
- Keep first line <= 72 chars when possible
- Optionally include a body (what and why, not how), separated by one blank line
- Optionally include footers (e.g., BREAKING CHANGE:, Closes: #123)

Project preference: the commit message must be entirely in English.

Context from user (diff/summary/intent):
{{args}}

Output format:
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]

Do not include backticks, quotes, or code fences in the output.
"""
